// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nqtwzctovxhnspcxcbth.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5xdHd6Y3RvdnhobnNwY3hjYnRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3Njk3MDEsImV4cCI6MjA2ODM0NTcwMX0.pszKNgV5j2TfOeup2hySG7RmEv9XT_2sdFHKbl2t0QY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});